# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.calc_genoprob_gbs <- function(countsA, countsB, rec_frac, error_prob1, error_prob2) {
    .Call(`_xoiGBS_calc_genoprob_gbs`, countsA, countsB, rec_frac, error_prob1, error_prob2)
}

addlog <- function(a, b) {
    .Call(`_xoiGBS_addlog`, a, b)
}

